### ISSUE TITLE
API proposal

### ISSUE THREAD

**Issue by renannprado** [jeffotoni/gcolor#1]
Having to instantiate a struct for each color you want to print isn't too much user friendly.
So I propose the following API:

```go
type ColoredPrinter interface {
    Print(Color, string, ...interface{})
}
```

Sample usage:

```go
printer.Print(RED_FG, "test string %s", "mytest")
```

**Comment by jeffotoni** [comment]
How would your printer structure be?

**Comment by renannprado** [comment]
I don't know the kind of information you want to put there, but certainly not the color.

**Comment by jeffotoni** [comment]
Let's try to implement your tip. Thanks for the collaboration.

**Comment by jeffotoni** [comment]
Beta of a new feature posted by colleague @renannprado, this is a version that has to be improved
